@startuml
title コンポネント凝集性の3原則
legend top
  いかにバランスを取るかがアーキテクトの腕の見せ所。

  プロジェクトやチームの状態によってベストは変わる。
  - 開発の初期段階ならREPよりもCCPが重要になる。
  - 成熟度が上がっていくと、REPが重要になる。
endlegend

(REP: 再利用・リリース等価の原則) as REP
note left: 再利用性のためのグループ化
(CCP: 閉鎖性共通の原則) as CCP
note left: 保守性のためのグループ化
(CRP: 全再利用の原則) as CRP
note right: 不要なリリースを減らすための分割

REP -- CCP :ここが強くなりすぎると、リリース作業が増加する
REP -- CRP :ここが強くなりすぎると、変更すべきコンポネントの増加する
CRP -- CCP :ここが強くなりすぎると、再利用性が低下する

@enduml
